apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
  namespace: bioapp
data:
  PG_USERNAME: ZXhhbXBsZQ==
  SESSION_SECRET: ZXhhbXBsZQ==
  AUTH_SECRET: ZXhhbXBsZQ==
  eth_pri: ZXhhbXBsZQ==
  EMAIL_clientSecret: ZXhhbXBsZQ==
  EMAIL_PASSWORD: ZXhhbXBsZQ==
  EMAIL_clientId: ZXhhbXBsZQ==
  EMAIL_refresh: ZXhhbXBsZQ==
  EMAIL_ACCOUNT: ZXhhbXBsZQ==
  EMAIL_SECRET: ZXhhbXBsZQ==
  EMAIL_accesstoken: ZXhhbXBsZQ==

