apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
  labels:
    app: backend
  namespace: bioapp
type: Opaque
data:
  biological-324006-firebase-adminsdk-4snru-e6da79fa36.json: "GOOGLE SERVICE ACCOUNT FILE BASE64"