apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: bioapp
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt
spec:
  rules:
     - host: bioapp-backend.yikuo.dev
       http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-sv
                port:
                  number: 8080
    
  tls:
    - secretName: bioapp-tls
      hosts:
        - bioapp-backend.yikuo.dev

