apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt
spec:
  rules:
     - host: "bioapp-kibana.yikuo.dev"
       http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601
    
  tls:
    - secretName: bioapp-kibana-tls
      hosts:
        - bioapp-kibana.yikuo.dev

